name: Unix Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Format files
        run: find exe include test -type f -a \( -name "*.cc" -o -name "*.h" \) -print0 | xargs -0 clang-format-10 -i

      - name: Check for differences
        run: |
          git status --porcelain
          git status --porcelain | xargs -I {} -0 test -z \"{}\"

  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Clang 11 Release
            cxx: clang++-11
            cc: clang-11
            mode: Release
            cxxflags: -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      # ==== INSTALL ====
      - name: Update APT
        if: matrix.config.os != 'macos-latest'
        run: sudo apt-get update

      - name: Install LLVM
        if: matrix.config.os != 'macos-latest' && matrix.config.cc == 'clang-11'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 11
          rm llvm.sh
          sudo apt-get install -y --no-install-recommends libc++-11-dev libc++abi-11-dev clang-tidy-11

      # ==== BUILD ====
      - name: CMake
        run: |
          cmake \
            -G Ninja -S . -B build \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_CXX_FLAGS=${{ matrix.config.cxxflags }} \
            -DCMAKE_CXX_LINKER_FLAGS=${{ matrix.config.ldflags }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }} \
            -DIFCGEOM_LINT=${{ matrix.config.lint }}

      - name: Build
        run: |
          cd build
          ninja ifcgeom-test

      # ==== TESTS ====
      - name: Run Tests
        run: ./build/ifcgeom-test