name: Unix Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Format files
        run: find exe include test -type f -a \( -name "*.cc" -o -name "*.h" \) -print0 | xargs -0 clang-format-10 -i

      - name: Check for differences
        run: |
          git status --porcelain
          git status --porcelain | xargs -I {} -0 test -z \"{}\"

  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Clang Tidy
            cxx: clang++-10
            cc: clang-10
            mode: Debug
            lint: true
            os: ubuntu-latest
    steps:
      # ==== SETUP ====
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Tools
        run: |
          apt-get install
            clang++-10

      # ==== BUILD ====
      - name: CMake
        run: |
          cmake \
            -G Ninja -S . -B build \
            -DBUILD_SHARED_LIBS=OFF \
            -DCGAL_HEADER_ONLY=1 \
            -DCGAL_NO_GMP=1 \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }} \
            -DIFCGEOM_LINT=${{ matrix.config.lint }}

      - name: Build
        run: |
          cd build
          ninja ifcgeom-test

      # ==== TESTS ====
      - name: Run Tests
        run: ./build/ifcgeom-test